name: 🚀 Request to run code
description: Submit a request to run code against TED data
title: "[Request] "
labels: [request]
assignees: []

body:
  - type: input
    id: repo_link
    attributes:
      label: 🔗 Link to repo
      description: Paste the URL of the repository containing the code to be run.
      placeholder: "https://github.com/org/repo-name"
    validations:
      required: true

  - type: textarea
    id: files_to_release
    attributes:
      label: 📦 Files to release
      description: List the paths of files to be released.
      placeholder: |
        e.g.
        - ouptuts/table.csv
        - ouptuts/chart.csv
    validations:
      required: true
